name: Release

on:
  push:
    branches:
      - master
      - release-*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'http://localhost:4873'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Configure Git
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"

      - name: Lerna version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn lerna version --conventional-commits --yes

      - name: Publish to local npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn lerna publish from-package --yes --no-verify-access --registry http://localhost:4873

      - name: Push changes
        run: git push --follow-tags
